In [122]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies = pd.read_csv('./data/tmdb_5000_movies.csv')
movies_df = movies[['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']]
movies_df.head(1)

id   title                                             genres  \
0  19995  Avatar  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

   vote_average  vote_count  popularity  \
0           7.2       11800  150.437577   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...

In [123]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [124]:
# literal_eval:문자열을 Python 객체로 변환
import ast

str_dict = "{'a': 3, 'b': 5}"
print(type(str_dict))           # <type 'str'>

convert_dict = ast.literal_eval(str_dict)

print(type(convert_dict))   # <type 'dict'>
print(convert_dict['a'])      #  3
print(convert_dict['b'])      #  5

<class 'str'>
<class 'dict'>
3
5


In [125]:
# literal_eval
import ast

str_dict = '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
print(type(str_dict))           # <type 'str'>

convert_dict = ast.literal_eval(str_dict)

print(type(convert_dict))    # <class 'list'>
print(convert_dict[0])       # {'id': 28, 'name': 'Action'}
print(type(convert_dict[0])) # <class 'dict'>
print(convert_dict[1])       # {'id': 12, 'name': 'Adventure'}

<class 'str'>
<class 'list'>
{'id': 28, 'name': 'Action'}
<class 'dict'>
{'id': 12, 'name': 'Adventure'}


In [126]:
# 장르만 추출
str_dict = '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"},\
{"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
convert_dict = ast.literal_eval(str_dict)
print(convert_dict)

for item in convert_dict:  # {"id": 28, "name": "Action"}...
    print(item['name'])

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]
Action
Adventure
Fantasy
Science Fiction


In [127]:
movies_df['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                   []
4802                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4803, dtype: object

In [128]:
print(type(movies_df['genres']))
print(type(movies_df['genres'][0]))
print(type(movies_df['genres'][0][0]))

<class 'pandas.core.series.Series'>
<class 'str'>
<class 'str'>


In [129]:
from ast import literal_eval

# genres 변수에 literal_eval 함수 호출
movies_df['genres'] = movies_df['genres'].apply(literal_eval) 
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval) 
movies_df[['genres', 'keywords']][:3]

genres  \
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                            keywords  
0  [{'id': 1463, 'name': 'culture clash'}, {'id':...  
1  [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...  
2  [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...

In [130]:
print(type(movies_df['genres']))
print(type(movies_df['genres'][0]))
print(type(movies_df['genres'][0][0]))

<class 'pandas.core.series.Series'>
<class 'list'>
<class 'dict'>


In [131]:
# lambda: 함수를 분리하여 선언하지 않아도 함수기능이 작동됨.
# name 속성의 값만 분리
# movies_df['genres']
# ↓
# x: [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
# ↓
# y: {"id": 28, "name": "Action"}
# ↓
# y['name'] 
movies_df['genres'] = movies_df['genres'].apply(lambda x:[y['name'] for y in x]) 
movies_df['keywords'] = movies_df['keywords'].apply(lambda x:[y['name'] for y in x]) 
movies_df[['genres', 'keywords']][:3]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   

                                            keywords  
0  [culture clash, future, space war, space colon...  
1  [ocean, drug abuse, exotic island, east india ...  
2  [spy, based on novel, secret agent, sequel, mi...

In [132]:
# CountVectorizer를 적용하기 위해 공백문자로 word 단위가 구분되는 문자열로 변환
# genres_literal 변수가 없음으로 새로 추가
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x:(' ').join(x))
print(movies_df['genres_literal'][0:10])

0    Action Adventure Fantasy Science Fiction
1                    Adventure Fantasy Action
2                      Action Adventure Crime
3                 Action Crime Drama Thriller
4            Action Adventure Science Fiction
5                    Fantasy Action Adventure
6                            Animation Family
7            Action Adventure Science Fiction
8                    Adventure Fantasy Family
9                    Action Adventure Fantasy
Name: genres_literal, dtype: object


In [133]:
from sklearn.feature_extraction.text import CountVectorizer

# min_df : 정수 또는 [0.0, 1.0] 사이의 실수. 디폴트 1
# 단어장에 포함되기 위한 최소 빈도
# ngram_range : (min_n, max_n) n-그램 범위로 단어의 묶을을 1~2개로 묶음.
count_vect = CountVectorizer()
# count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(count_vect.vocabulary_)# 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

{'action': 0, 'adventure': 1, 'fantasy': 8, 'science': 17, 'fiction': 9, 'crime': 4, 'drama': 6, 'thriller': 18, 'animation': 2, 'family': 7, 'western': 21, 'comedy': 3, 'romance': 16, 'horror': 12, 'mystery': 15, 'history': 11, 'war': 20, 'music': 14, 'documentary': 5, 'foreign': 10, 'tv': 19, 'movie': 13}


In [134]:
print(type(genre_mat)) # <class 'scipy.sparse.csr.csr_matrix'>
print(genre_mat.shape) # 영화수: 4803, 장르: 22
print(genre_mat[0:2]) 
# 0    Action Adventure Fantasy Science Fiction
#   (영화번호, 장르 index 번호) 1: 해당
#   (0, 0)  1  Action
#   (0, 1)  1  adventure
#   (0, 8)  1  fantasy
#   (0, 17) 1  science
#   (0, 9)  1  fiction

<class 'scipy.sparse.csr.csr_matrix'>
(4803, 22)
  (0, 0)	1
  (0, 1)	1
  (0, 8)	1
  (0, 17)	1
  (0, 9)	1
  (1, 0)	1
  (1, 1)	1
  (1, 8)	1


In [135]:
# min_df : 정수 또는 [0.0, 1.0] 사이의 실수. 디폴트 1
# 단어장에 포함되기 위한 최소 빈도
# ngram_range : (min_n, max_n) n-그램 범위로 단어의 묶을을 1~2개로 묶음.
# count_vect = CountVectorizer()
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(count_vect.vocabulary_)# 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

{'action': 0, 'adventure': 16, 'fantasy': 124, 'science': 232, 'fiction': 138, 'action adventure': 1, 'adventure fantasy': 24, 'fantasy science': 135, 'science fiction': 233, 'fantasy action': 125, 'crime': 64, 'adventure crime': 20, 'drama': 90, 'thriller': 234, 'action crime': 4, 'crime drama': 68, 'drama thriller': 106, 'adventure science': 29, 'animation': 33, 'family': 109, 'animation family': 38, 'fantasy family': 130, 'action science': 12, 'adventure action': 17, 'action thriller': 13, 'thriller crime': 238, 'western': 265, 'adventure western': 32, 'adventure family': 23, 'family fantasy': 115, 'fiction action': 139, 'action fantasy': 7, 'comedy': 44, 'action comedy': 3, 'comedy science': 59, 'adventure drama': 22, 'drama action': 91, 'romance': 214, 'drama romance': 104, 'romance thriller': 228, 'thriller action': 235, 'fiction thriller': 150, 'adventure thriller': 30, 'fantasy adventure': 126, 'family adventure': 111, 'adventure comedy': 19, 'thriller science': 247, 'family co

In [136]:
print(genre_mat.shape) # 영화수: 4803, 장르: 276 <- 장르 조합으로 22개에서 증가됨
print(genre_mat[0:1]) 
# 0    Action Adventure Fantasy Science Fiction 영화가 속하는 장르들로 구성됨

(4803, 276)
  (0, 0)	1
  (0, 16)	1
  (0, 124)	1
  (0, 232)	1
  (0, 138)	1
  (0, 1)	1
  (0, 24)	1
  (0, 135)	1
  (0, 233)	1


In [137]:
print(type(genre_mat.toarray()))
print(genre_mat.toarray().shape)
print(genre_mat.toarray()[0:2]) # 첫번째 영화가 속한 장르가 희소 행렬 형태로 출력됨.

<class 'numpy.ndarray'>
(4803, 276)
[[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0

### 코사인 유사도 계산, 장르 유사도 계산

In [138]:
#             고요의 바다  오징어       지옥
# 고요의 바다  1           0.59628479   0.4472136 
# 오징어       0.59628479  1            0.4             
# 지옥         0.4472136   0.4          1

In [139]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat) # 코사인 유사도
print(genre_sim.shape)
print(genre_sim[:5])
# (4803, 4803)
#         Avatar       Pirates      Spectre
# Avatar  1.           0.59628479   0.4472136  ...
# Pirates 0.59628479   1.           0.4        ... 
# Spectre 0.4472136    0.4          1.         ... 

#  1: Avatar:Avatar
#  0.59628479: Avatar:Pirates of the Caribbean: At World's End
#  0.4472136: Avatar:Spectre

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 [0.12598816 0.16903085 0.3380617  ... 0.12598816 0.         0.        ]
 [0.75592895 0.3380617  0.50709255 ... 0.         0.         0.        ]]


In [140]:
import numpy as np
a = np.array([4,2,1,7]) 
sort_index = a.argsort() # 데이터에 대한 index가 오름차순으로 할당
sort_index

array([2, 1, 0, 3], dtype=int64)

In [141]:
print(a[sort_index]) # index 순으로 데이터 출력
print(np.array([4,2,1,7]).argsort()[:])
print(sort_index[::-1])    # 내림 차순
print(a[sort_index[::-1]]) # 내림 차순 데이터 출력

[1 2 4 7]
[2 1 0 3]
[3 0 1 2]
[7 4 2 1]


In [142]:
# 2차원의 형태인 코사인 유사도 결과를
# 각각의 행안에서 내림차순으로 컬럼의 값을 내림차순 정렬하는 index 산출
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1] 
print(genre_sim_sorted_ind[:5]) # index 확인

[[   0 3494  813 ... 3038 3037 2401]
 [ 262    1  129 ... 3069 3067 2401]
 [   2 1740 1542 ... 3000 2999 2401]
 [2195 1850 3316 ...  887 2544 4802]
 [ 102 2995   56 ... 3046 3045 2401]]


### 영화 장르를 이용한 추천

In [143]:
# df: 데이터, sorted_ind: 코사인 유사도가 계산된후 내림 차순 정렬된 index 배열 
# title_name: 유사도를 찾을 기준 영화명, top_n=10: 유사도가 높은 10개의 영화
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    # 인자로 입력된 movies_df DataFrame에서 'title' 칼럼이 입력된 title_name 값인 DataFrame 추출
    title_movie = df[df['title'] == title_name]
    display('1)', title_movie) # 데이터 타입의 출력 형식을 유지하며 출력됨
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출
    title_index = title_movie.index.values # 영화명 index
    print('2)', title_index) # Avata: 0
    print('3) sorted_ind.shape:', sorted_ind.shape)
    
    # sorted_ind[3337, :10]: 내림 차순된 index 10개 산출
    similar_indexes = sorted_ind[title_index, :(top_n)] # 영화명 index, 컬럼 10개
    
    # 추출된 top_n index 출력. top_n index는 2차원 데이터임.
    # DataFrame 에서 index로 사용하기 위해서 1차원 array로 변경
    print('4)', similar_indexes)
    
    similar_indexes = similar_indexes.reshape(-1) # 현재 차원보다 한차원 내림
    print('5)', similar_indexes)
    
    return df.iloc[similar_indexes] # index에 해당하는 관측치 return

In [144]:
# movies_df: 데이터
# genre_sim_sorted_ind: 코사인 유사도가 계산된후 내림 차순 정렬된 index 배열 
# 'The Godfather': 유사도를 찾을 기준 영화명
# 10: 유사도가 높은 10개의 영화
similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'Avatar', 10)

'1)'

id   title                                         genres  vote_average  \
0  19995  Avatar  [Action, Adventure, Fantasy, Science Fiction]           7.2   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [culture clash, future, space war, space colon...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction

2) [0]
3) sorted_ind.shape: (4803, 4803)
4) [[   0 3494  813  870   46   14 1296 1652  419  420]]
5) [   0 3494  813  870   46   14 1296 1652  419  420]


In [145]:
similar_movies[['title', 'vote_average', 'vote_count']]

title  vote_average  vote_count
0                                        Avatar           7.2       11800
3494  Beastmaster 2: Through the Portal of Time           4.6          17
813                                    Superman           6.9        1022
870                                 Superman II           6.5         629
46                   X-Men: Days of Future Past           7.5        6032
14                                 Man of Steel           6.5        6359
1296                               Superman III           5.3         490
1652                       Dragonball Evolution           2.9         462
419                                      Jumper           5.9        1799
420                 Hellboy II: The Golden Army           6.5        1527

In [146]:
similar_movies[['title', 'vote_average', 'vote_count']].sort_values('vote_average', ascending=False)
# 자기 자신을 추천하며 평점이 낮은 영화도 추천하는 기능을 개선할 필요가 있음.

title  vote_average  vote_count
46                   X-Men: Days of Future Past           7.5        6032
0                                        Avatar           7.2       11800
813                                    Superman           6.9        1022
870                                 Superman II           6.5         629
14                                 Man of Steel           6.5        6359
420                 Hellboy II: The Golden Army           6.5        1527
419                                      Jumper           5.9        1799
1296                               Superman III           5.3         490
3494  Beastmaster 2: Through the Portal of Time           4.6          17
1652                       Dragonball Evolution           2.9         462

In [147]:
similar_movies.head(1)

id   title                                         genres  vote_average  \
0  19995  Avatar  [Action, Adventure, Fantasy, Science Fiction]           7.2   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [culture clash, future, space war, space colon...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction

In [148]:
# 값을 높이면 평점 투표 횟수가 많은 영화에 더 많은 가중 평점을 부여
percentile = 0.6 # 60%, 높을 수록 평가를 많이 받은 검증된 영화 추천

# 60%의 위치에 해당하는 투표수 산출
m = movies['vote_count'].quantile(percentile) 
C = movies['vote_average'].mean() # 전체 영화 평균 평점

def weighted_vote_average(record):
    v = record['vote_count']   # 개별 영화에 평점을 투표한 횟수
    R = record['vote_average'] # 개별 영화에 대한 평균 평점
    
    return ((v/(v+m))*R) + ((m/(m+v))*C)

# 가중 평점의 처리 후 weighted_vote 변수 생성
similar_movies['weighted_vote'] = similar_movies.apply(weighted_vote_average, axis=1) # 컬럼에 적용
similar_movies[['title', 'vote_average', 'weighted_vote', 'vote_count']].sort_values('weighted_vote', ascending=False)[:10]

title  vote_average  weighted_vote  \
46                   X-Men: Days of Future Past           7.5       7.418594   
0                                        Avatar           7.2       7.166301   
813                                    Superman           6.9       6.685190   
14                                 Man of Steel           6.5       6.477564   
420                 Hellboy II: The Golden Army           6.5       6.420421   
870                                 Superman II           6.5       6.348901   
3494  Beastmaster 2: Through the Portal of Time           4.6       6.026658   
419                                      Jumper           5.9       5.932796   
1296                               Superman III           5.3       5.640923   
1652                       Dragonball Evolution           2.9       4.320022   

      vote_count  
46          6032  
0          11800  
813         1022  
14          6359  
420         1527  
870          629  
3494          17  
419         1799  
1296         490  
1652         462

In [156]:
# 기준이 되는 영화는 제외하는 함수
# df: 데이터, sorted_ind: 코사인 유사도가 계산된후 내림 차순 정렬된 index 배열 
# title_name: 유사도를 찾을 기준 영화명, top_n=10: 유사도가 높은 10개의 영화
def find_sim_movie2(df, sorted_ind, title_name, top_n=10):
    top_n = top_n + 1 # 기준이되는 영화는 제외함으로 1건을 추가함
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 칼럼이 입력된 title_name 값인 DataFrame 추출
    title_movie = df[df['title'] == title_name]
    display('1)', title_movie) # 데이터 타입의 출력 형식을 유지하며 출력됨
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출
    title_index = title_movie.index.values # 영화명 index
    print('2)', title_index) # Avata: 0
    print('3) sorted_ind.shape:', sorted_ind.shape)
    
    # sorted_ind[3337, :10]: 내림 차순된 index 10개 산출
    similar_indexes = sorted_ind[title_index, :(top_n)] # 영화명 index, 컬럼 10개
    
    # 추출된 top_n index 출력. top_n index는 2차원 데이터임.
    # DataFrame 에서 index로 사용하기 위해서 1차원 array로 변경
    print('4)', similar_indexes)
    
    similar_indexes = similar_indexes.reshape(-1) # 현재 차원보다 한차원 내림
    print('5)', similar_indexes)
    
    similar_indexes = similar_indexes[similar_indexes != title_index]
    print('6)', similar_indexes)
    
    return df.iloc[similar_indexes] # index에 해당하는 관측치 return

In [160]:
# similar_movies = find_sim_movie2(movies_df, genre_sim_sorted_ind, 'Avatar', 10)
# similar_movies = find_sim_movie2(movies_df, genre_sim_sorted_ind, 'Superman', 10)
similar_movies = find_sim_movie2(movies_df, genre_sim_sorted_ind, 'Star Wars: Episode III - Revenge of the Sith', 10)
# similar_movies = find_sim_movie2(movies_df, genre_sim_sorted_ind, 'Star', 10) # ERROR

similar_movies['weighted_vote'] = similar_movies.apply(weighted_vote_average, axis=1) # 컬럼에 적용
similar_movies[['title', 'vote_average', 'weighted_vote', 'vote_count']].sort_values('weighted_vote', ascending=False)[:10]

'1)'

id                                         title  \
229  1895  Star Wars: Episode III - Revenge of the Sith   

                                   genres  vote_average  vote_count  \
229  [Science Fiction, Adventure, Action]           7.1        4116   

     popularity                                           keywords  \
229   44.108427  [showdown, death star, vision, cult figure, ha...   

                                              overview  \
229  Years after the onset of the Clone Wars, the n...   

                       genres_literal  
229  Science Fiction Adventure Action

2) [229]
3) sorted_ind.shape: (4803, 4803)
4) [[ 229  466  490   51 1990  183   26   52  495 2372 2912]]
5) [ 229  466  490   51 1990  183   26   52  495 2372 2912]
6) [ 466  490   51 1990  183   26   52  495 2372 2912]


title  vote_average  weighted_vote  \
1990           The Empire Strikes Back           8.2       8.075133   
2912                         Star Wars           8.1       7.993727   
183    The Hunger Games: Catching Fire           7.4       7.329476   
26          Captain America: Civil War           7.1       7.050980   
51                         Pacific Rim           6.7       6.656427   
52      Transformers: Dark of the Moon           6.1       6.099210   
2372                         Megaforce           3.5       5.991230   
466                   The Time Machine           5.8       5.908032   
495   Journey 2: The Mysterious Island           5.8       5.877247   
490                 A Sound of Thunder           4.8       5.794102   

      vote_count  
1990        5879  
2912        6624  
183         6495  
26          7241  
51          4794  
52          3299  
2372          15  
466          631  
495         1030  
490          111