### 추천 시스템 제작(도서)

In [7]:
# %autosave 0
import warnings
warnings.filterwarnings(action='ignore')

import os

import numpy as np
import pandas as pd

from IPython.display import Image

from tensorflow.keras.models import load_model  # model 사용

import platform 

if (platform.system() == 'Windows'):  # Windows, Linux, Darwin
    path = '.' # Local
else:    
    path = '/content/drive/My Drive/ai7/dnn/recommendation' # Colab
    
model = load_model(path + '/Book.h5')    
# select.append(1) # 1. Do it! 점프 투 파이썬  2. 저스트고 유럽 5개국  3. 어린 왕자
# select.append(1) # 1. 모두의 알고리즘 with 파이썬 2. 유럽 여행 바이블  3. 세상에 나쁜 사람은 없다
# select.append(2) # 1. 파이썬으로 배우는 통계학 교과서  2. 알프스 자동차 여행 66  3. 2061년

In [8]:
sample = [[1, 1, 1]]
sample = sample + [[2, 2, 2]]
sample

[[1, 1, 1], [2, 2, 2]]

In [9]:
# select = [1, 1, 1] # 개발 관련 도서 추천 필요
# select = [1, 2, 1] # 개발 관련 도서 추천 필요
# select = [1, 1, 2] # 개발 관련 도서 추천 필요
# select = [2, 1, 1] # 개발 관련 도서 추천 필요
# select = [3, 1, 1] # 개발 관련 도서 추천 필요
# select = [2, 2, 2] # 해외 여행 관련 도서 추천 필요
# select = [1, 2, 2] # 해외 여행 관련 도서 추천 필요
# select = [2, 1, 2] # 해외 여행 관련 도서 추천 필요
# select = [2, 2, 1] # 해외 여행 관련 도서 추천 필요
# select = [3, 3, 3] # 소설 관련 도서 추천 필요
# select = [1, 3, 3]   # 소설 관련 도서 추천 필요
sample = [[1, 1, 1],[1, 2, 1],[1, 1, 2],[2, 1, 1],[3, 1, 1], [1, 3, 1]]
sample = sample + [[2, 2, 2],[1, 2, 2],[2, 1, 2],[2, 2, 1]]
sample = sample + [[3, 3, 3], [1, 3, 3], [3, 1, 3], [3, 3, 1], [2, 3, 3], [3, 2, 3], [3, 3, 2]]

for select in sample:
    print(select)

    X = []
    for i in range(0, 3): # 평가 횟수 3번, 0 ~ 2
        for j in range(1, 4): # 평가 항목수 3개
            # print(i, j)
            # 선택한 번호화 같은 경우만 1을 할당
            # 사용자가 입력한 1은 배열 index 0에 해당함.
            if (select[i] == j): # 1 == 1
                X.append(0.8)      # 1                       
            else:
                X.append(0.1)      # 0,1              

    data = np.array([np.array(X)]) # 입력 데이터는 ndarray 타입의 2차원이어야함, 행 방향
    p = model.predict(data)  # 모델 사용, 2차원 데이터 전달
    print(p)
    index = np.argmax(p[0])  # 가장 높은 값의 index 산출, 가장 확률이 높은 값의 index
    if index == 0:
        label = '개발 관련 도서'
    elif index == 1:
        label = '해외 여행 관련 도서'
    elif index == 2:
        label = '소설 관련 도서'

    print(label + ' 추천 필요' +'\n') 

[1, 1, 1]
[[0.82058233 0.12393649 0.05548111]]
개발 관련 도서 추천 필요

[1, 2, 1]
[[0.6451483  0.3021424  0.05270935]]
개발 관련 도서 추천 필요

[1, 1, 2]
[[0.6346957  0.2829135  0.08239079]]
개발 관련 도서 추천 필요

[2, 1, 1]
[[0.51136315 0.36181262 0.12682427]]
개발 관련 도서 추천 필요

[3, 1, 1]
[[0.6669884  0.11952685 0.2134848 ]]
개발 관련 도서 추천 필요

[1, 3, 1]
[[0.54222417 0.18290505 0.27487075]]
개발 관련 도서 추천 필요

[2, 2, 2]
[[0.10113057 0.8084394  0.09043002]]
해외 여행 관련 도서 추천 필요

[1, 2, 2]
[[0.35322937 0.5774757  0.0692948 ]]
해외 여행 관련 도서 추천 필요

[2, 1, 2]
[[0.2459778  0.60754013 0.14648205]]
해외 여행 관련 도서 추천 필요

[2, 2, 1]
[[0.25189948 0.65368766 0.0944128 ]]
해외 여행 관련 도서 추천 필요

[3, 3, 3]
[[0.0225507  0.05697213 0.9204771 ]]
소설 관련 도서 추천 필요

[1, 3, 3]
[[0.04574265 0.07702421 0.8772331 ]]
소설 관련 도서 추천 필요

[3, 1, 3]
[[0.06363722 0.05539936 0.88096344]]
소설 관련 도서 추천 필요

[3, 3, 1]
[[0.22348154 0.10579676 0.6707217 ]]
소설 관련 도서 추천 필요

[2, 3, 3]
[[0.01371448 0.10698704 0.8792985 ]]
소설 관련 도서 추천 필요

[3, 2, 3]
[[0.04671529 0.16425784 0.7890269