### 추천 시스템 제작(도서)

In [31]:
# %autosave 0
import warnings
warnings.filterwarnings(action='ignore')

import os

import numpy as np
import pandas as pd

from IPython.display import Image

from tensorflow.keras.models import load_model  # model 사용

import platform 

if (platform.system() == 'Windows'):  # Windows, Linux, Darwin
    path = '.' # Local
else:    
    path = '/content/drive/My Drive/ai7/dnn/recommendation' # Colab

In [32]:
model = load_model(path + '/Book.h5')

In [33]:
# 1행의 데이터를 읽어 2차원의 형태로 변환하여 데이터 준비
data = np.loadtxt(path + '/user1.csv', delimiter=',', skiprows=1, dtype=np.float64)
print(type(data))
print(data.shape)
print(data)
data = np.array([data]) # 2차원, 행 방향
# data = np.reshape(data, (data.shape[0], 1)) # 2차원, 열 방향
print(data)

<class 'numpy.ndarray'>
(9,)
[0.8 0.1 0.1 0.8 0.1 0.1 0.8 0.1 0.1]
[[0.8 0.1 0.1 0.8 0.1 0.1 0.8 0.1 0.1]]


In [34]:
print('데이터:', data[0])     # 첫번째 데이터행

p = model.predict(data)  # 모델 사용, 2차원 데이터 전달

print('p.shape:', p.shape) # 출력 결과는 1행 3열
# 확률 0 ~ 1사이의 실수값
print('예측값:', p[0]) 
print('예측값:{0:.7f} {1:.7f} {2:.7f}'.format(p[0][0], p[0][1], p[0][2])) 

데이터: [0.8 0.1 0.1 0.8 0.1 0.1 0.8 0.1 0.1]
p.shape: (1, 3)
예측값: [0.82058233 0.12393649 0.05548111]
예측값:0.8205823 0.1239365 0.0554811


In [35]:
# 모델 사용을 함수로 변경
# 0: 개발 관련 도서
# 1: 해외 여행 관련 도서
# 2: 소설 관련 도서
def recommendation(fname):
    data = np.loadtxt(path + '/' + fname, delimiter=',', skiprows=1, dtype=np.float64)
    data = np.array([data]) # 2차원 배열로 변경, 행 방향
    
    p = model.predict(data)  # 2차원 데이터 전달하여 분류에 포함될 확률을 2차원 배열로 전달받음
    
    print(fname)
    print(p[0]) # 예측된 확률 출력
    
    index = np.argmax(p[0]) # 가장 큰 값이 있는 배열의 index return
    print('가장 큰 값이 있는 배열의 index:', index)
    if index == 0:
        label = '개발 관련 도서'
    elif index == 1:
        label = '해외 여행 관련 도서'
    elif index == 2:
        label = '소설 관련 도서'
        
    return label

In [36]:
print(recommendation('user1.csv'))

user1.csv
[0.82058233 0.12393649 0.05548111]
가장 큰 값이 있는 배열의 index: 0
개발 관련 도서


<TABLE><TR>
  <TD style='vertical-align: middle'>
      <img src='./images/v11.jpg' style='float:left; height: 200px'>
  </TD>
  <TD style='vertical-align: middle'>
      <img src='./images/v21.jpg' style='float:left; height: 200px'>
  </TD>
  <TD style='vertical-align: middle'>
      <img src='./images/v31.jpg' style='float:left; height: 200px'>
  </TD>
</TR></TABLE>

In [37]:
select = [] # 선택 값 저장
select1 = int(input('1. Do it! 점프 투 파이썬  2. 저스트고 유럽 5개국  3. 어린 왕자'))
select.append(select1)

1. Do it! 점프 투 파이썬  2. 저스트고 유럽 5개국  3. 어린 왕자1


<TABLE><TR>
  <TD style='vertical-align: middle'>
      <img src='./images/v12.jpg' style='float:left; height: 200px'>
  </TD>
  <TD style='vertical-align: middle'>
      <img src='./images/v22.jpg' style='float:left; height: 200px'>
  </TD>
  <TD style='vertical-align: middle'>
      <img src='./images/v32.jpg' style='float:left; height: 200px'>
  </TD>
</TR></TABLE>

In [38]:
select2 = int(input('1. 모두의 알고리즘 with 파이썬 2. 유럽 여행 바이블  3. 세상에 나쁜 사람은 없다'))
select.append(select2)

1. 모두의 알고리즘 with 파이썬 2. 유럽 여행 바이블  3. 세상에 나쁜 사람은 없다3


<TABLE><TR>
  <TD style='vertical-align: middle'>
      <img src='./images/v13.jpg' style='float:left; height: 200px'>
  </TD>
  <TD style='vertical-align: middle'>
      <img src='./images/v23.jpg' style='float:left; height: 200px'>
  </TD>
  <TD style='vertical-align: middle'>
      <img src='./images/v33.jpg' style='float:left; height: 200px'>
  </TD>
</TR></TABLE>

In [39]:
select3 = int(input('1. 파이썬으로 배우는 통계학 교과서  2. 알프스 자동차 여행 66  3. 2061년'))
select.append(select3)
print(select1, select2, select3)
print(select) #list

1. 파이썬으로 배우는 통계학 교과서  2. 알프스 자동차 여행 66  3. 2061년1
1 3 1
[1, 3, 1]


### 입력받은 값 1,1,1을 입력 데이터 형식 1,0,0,1,0,0,1,0,0 으로 변환하는 과정
### 입력받은 값 2,2,2를 입력 데이터 형식 0,1,0,0,1,0,0,1,0 으로 변환하는 과정

In [40]:
for j in range(1, 4):
    print(j)

1
2
3


In [41]:
X = []  # list
# 선택 값중에 첫번째 값
for j in range(1, 4): # 1 ~ 3까지 발생
    if (select[0] == j): # 1 == 1, 1 == 2, 1 == 3
        X.append(0.8)   
    else:
        X.append(0.1)
        
print(X)        

[0.8, 0.1, 0.1]


In [42]:
# 선택 값중에 두번째 값
for j in range(1, 4): # 1 ~ 3까지 발생
    if (select[1] == j): # 1 == 1, 1 == 2, 1 == 3
        X.append(0.8)      # 1       0       0 
    else:
        X.append(0.1)
        
print(X)      

[0.8, 0.1, 0.1, 0.1, 0.1, 0.8]


In [43]:
# 선택 값중에 세번째 값
for j in range(1, 4): # 1 ~ 3까지 발생
    if (select[2] == j): # 1 == 1, 1 == 2, 1 == 3
        X.append(0.8)      # 1       0       0 
    else:
        X.append(0.1)
        
print(X)      

[0.8, 0.1, 0.1, 0.1, 0.1, 0.8, 0.8, 0.1, 0.1]


In [44]:
# 3개의 for문이 결합된 형태
X = []
for i in range(0, 3): # 평가 횟수 3번, 0 ~ 2
    for j in range(1, 4): # 평가 항목수 3개
        # print(i, j)
        # 선택한 번호화 같은 경우만 1을 할당
        # 사용자가 입력한 1은 배열 index 0에 해당함.
        if (select[i] == j): # 1 == 1
            X.append(0.8)      # 1                       
        else:
            X.append(0.1)      # 0,0                
            
print(X)            
print(np.array([np.array(X)])) # 1차원 list -> 2차원 ndarray 배열로 변경

[0.8, 0.1, 0.1, 0.1, 0.1, 0.8, 0.8, 0.1, 0.1]
[[0.8 0.1 0.1 0.1 0.1 0.8 0.8 0.1 0.1]]


In [45]:
data = np.array([np.array(X)]) # 입력 데이터는 ndarray 타입의 2차원이어야함, 행 방향
print(data)
p = model.predict(data)  # 모델 사용, 2차원 데이터 전달
print(p)
index = np.argmax(p[0])  # 가장 높은 값의 index 산출, 가장 확률이 높은 값의 index
if index == 0:
    label = '개발 관련 도서'
elif index == 1:
    label = '해외 여행 관련 도서'
elif index == 2:
    label = '소설 관련 도서'

print(label + ' 추천 필요') 
# 1 1 1: 개발 관련 도서 추천 필요
# 1 2 1: 개발 관련 도서 추천 필요
# 1 1 2: 해외 여행 관련 도서 추천 필요 X
# 2 1 1: 해외 여행 관련 도서 추천 필요 X
# 2 2 2: 해외 여행 관련 도서 추천 필요
# 2 3 3: 해외 여행 관련 도서 추천 필요 X
# 1 3 3: 해외 여행 관련 도서 추천 필요 X
# 3 3 1: 해외 여행 관련 도서 추천 필요 X
# 3 3 3: 소설 관련 도서 추천 필요

[[0.8 0.1 0.1 0.1 0.1 0.8 0.8 0.1 0.1]]
[[0.54222417 0.18290505 0.27487075]]
개발 관련 도서 추천 필요


#### 딥러닝 모델을 이용하여 고객의 특성이 파악됨
#### 기업에서의 추천 시스템은 비공개로 개발되는 알고리즘이 다양함
#### DBMS에 사용자가 구입한 상품이면 추천 상품에서 제외 시켜야함.